INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (1, '이동영짱1', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (2, '이동영짱2', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (3, '이동영짱3', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (4, '이동영짱4', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (5, '이동영짱5', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (6, '이동영짱6', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (7, '이동영짱7', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (8, '이동영짱8', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (9, '이동영짱9', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (10, '이동영짱10', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (11, '이동영짱11', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (12, '이동영짱12', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (13, '이동영짱13', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (14, '이동영짱14', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (15, '이동영짱15', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (16, '이동영짱16', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (17, '이동영짱17', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (18, '이동영짱18', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (19, '이동영짱19', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (20, '이동영짱20', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (21, '이동영짱21', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (22, '이동영짱22', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (23, '이동영짱23', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (24, '이동영짱24', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (25, '이동영짱25', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (26, '이동영짱26', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (27, '이동영짱27', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (28, '이동영짱28', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (29, '이동영짱29', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (30, '이동영짱30', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (31, '이동영짱31', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (32, '이동영짱32', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (33, '이동영짱33', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (34, '이동영짱34', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (35, '이동영짱35', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (36, '이동영짱36', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (37, '이동영짱37', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (38, '이동영짱38', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (39, '이동영짱39', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (40, '이동영짱40', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (41, '이동영짱41', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (42, '이동영짱42', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (43, '이동영짱43', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (44, '이동영짱44', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (45, '이동영짱45', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (46, '이동영짱46', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (47, '이동영짱47', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (48, '이동영짱48', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (49, '이동영짱49', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (50, '이동영짱50', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (51, '이동영짱51', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (52, '이동영짱52', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (53, '이동영짱53', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (54, '이동영짱54', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (55, '이동영짱55', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (56, '이동영짱56', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (57, '이동영짱57', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (58, '이동영짱58', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (59, '이동영짱59', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (60, '이동영짱60', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (61, '이동영짱61', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (62, '이동영짱62', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (63, '이동영짱63', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (64, '이동영짱64', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (65, '이동영짱65', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (66, '이동영짱66', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (67, '이동영짱67', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (68, '이동영짱68', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (69, '이동영짱69', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (70, '이동영짱70', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (71, '이동영짱71', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (72, '이동영짱72', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (73, '이동영짱73', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (74, '이동영짱74', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (75, '이동영짱75', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (76, '이동영짱76', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (77, '이동영짱77', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (78, '이동영짱78', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (79, '이동영짱79', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (80, '이동영짱80', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (81, '이동영짱81', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (82, '이동영짱82', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (83, '이동영짱83', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (84, '이동영짱84', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (85, '이동영짱85', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (86, '이동영짱86', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (87, '이동영짱87', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (88, '이동영짱88', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (89, '이동영짱89', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (90, '이동영짱90', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (91, '이동영짱91', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (92, '이동영짱92', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (93, '이동영짱93', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (94, '이동영짱94', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (95, '이동영짱95', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (96, '이동영짱96', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (97, '이동영짱97', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (98, '이동영짱98', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (99, '이동영짱99', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (100, '이동영짱100', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);


commit;