
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (101, '이동영짱101', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (102, '이동영짱102', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (103, '이동영짱103', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (104, '이동영짱104', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (105, '이동영짱105', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (106, '이동영짱106', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (107, '이동영짱107', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (108, '이동영짱108', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (109, '이동영짱109', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (110, '이동영짱110', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (111, '이동영짱111', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (112, '이동영짱112', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (113, '이동영짱113', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (114, '이동영짱114', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (115, '이동영짱115', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (116, '이동영짱116', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (117, '이동영짱117', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (118, '이동영짱118', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (119, '이동영짱119', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (120, '이동영짱120', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (121, '이동영짱121', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (122, '이동영짱122', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (123, '이동영짱123', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (124, '이동영짱124', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (125, '이동영짱125', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (126, '이동영짱126', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (127, '이동영짱127', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (128, '이동영짱128', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (129, '이동영짱129', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (130, '이동영짱130', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (131, '이동영짱131', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (132, '이동영짱132', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (133, '이동영짱133', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (134, '이동영짱134', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (135, '이동영짱135', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (136, '이동영짱136', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (137, '이동영짱137', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (138, '이동영짱138', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (139, '이동영짱139', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (140, '이동영짱140', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (141, '이동영짱141', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (142, '이동영짱142', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (143, '이동영짱143', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (144, '이동영짱144', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (145, '이동영짱145', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (146, '이동영짱146', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (147, '이동영짱147', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (148, '이동영짱148', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (149, '이동영짱149', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (150, '이동영짱150', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (151, '이동영짱151', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (152, '이동영짱152', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (153, '이동영짱153', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (154, '이동영짱154', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (155, '이동영짱155', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (156, '이동영짱156', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (157, '이동영짱157', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (158, '이동영짱158', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (159, '이동영짱159', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (160, '이동영짱160', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (161, '이동영짱161', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (162, '이동영짱162', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (163, '이동영짱163', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (164, '이동영짱164', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (165, '이동영짱165', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (166, '이동영짱166', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (167, '이동영짱167', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (168, '이동영짱168', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (169, '이동영짱169', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (170, '이동영짱170', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (171, '이동영짱171', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (172, '이동영짱172', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (173, '이동영짱173', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (174, '이동영짱174', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (175, '이동영짱175', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (176, '이동영짱176', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (177, '이동영짱177', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (178, '이동영짱178', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (179, '이동영짱179', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (180, '이동영짱180', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (181, '이동영짱181', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (182, '이동영짱182', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (183, '이동영짱183', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (184, '이동영짱184', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (185, '이동영짱185', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (186, '이동영짱186', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (187, '이동영짱187', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (188, '이동영짱188', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (189, '이동영짱189', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (190, '이동영짱190', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (191, '이동영짱191', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (192, '이동영짱192', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (193, '이동영짱193', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (194, '이동영짱194', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (195, '이동영짱195', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (196, '이동영짱196', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (197, '이동영짱197', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (198, '이동영짱198', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (199, '이동영짱199', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (200, '이동영짱200', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);
INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (201, '이동영짱201', '카테고리', '공지사항', '공지사항 입니다.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);


INSERT INTO tbl_free (seq, writer, category, title, content, write_date, modify_date, total_count)
VALUES (202, '관리자', '카테고리', '테스트', '테스트.', TO_DATE('2023-05-11', 'YYYY-MM-DD'), null, 0);

commit;